export const C = {
  bg: "#f8fafc",
  card: "#ffffff",
  card2: "#f1f5f9",
  border: "#e2e8f0",
  accent: "#0056b3",
  gold: "#f5a623",
  green: "#10b981",
  blue: "#3b82f6",
  text: "#1e293b",
  muted: "#64748b",
  subtle: "#cbd5e1",
};

export const S = {
  page: {
    background: C.bg,
    minHeight: "100vh",
    fontFamily: "'Inter', sans-serif",
    color: C.text,
  },
  nav: {
    background: "#ffffff",
    borderBottom: `1px solid ${C.border}`,
    padding: "0 24px",
    height: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky" as const,
    top: 0,
    zIndex: 999,
  },
  card: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
  },
  btn: {
    border: "none",
    borderRadius: 10,
    padding: "12px 24px",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 14,
  },
  input: {
    background: "#ffffff",
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: "12px 16px",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  wrap: { maxWidth: 1200, margin: "0 auto", padding: "32px 24px" },
  col: { display: "flex", flexDirection: "column" as const, gap: 12 },
  flex: { display: "flex", alignItems: "center", gap: 12 },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(320px,1fr))",
    gap: 24,
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px,1fr))",
    gap: 20,
  },
  badge: { fontSize: 12, padding: "4px 10px", borderRadius: 30, fontWeight: 600 },
};
